sobek.locals.language.default=eng

debug=true

#OAuth2 Resource Server
shepet.oauth2.resourceserver.auth0.entur.partner.jwt.audience=${SHEPET_OAUTH2_RESOURCESERVER_AUTH0_ENTUR_PARTNER_JWT_AUDIENCE}
shepet.oauth2.resourceserver.auth0.entur.partner.jwt.issuer-uri=${SHEPET_OAUTH2_RESOURCESERVER_AUTH0_ENTUR_PARTNER_JWT_ISSUER_URI}


# netex.valid.codespaces.list={'AKT','ATB','ASH','AVI','BNR','BEF','BOR','BSR','BRA','NYC','COL','TEL','FJT','FLI','FLT','FTR','FLB','OSC','MOR','GFS','GLO','GOA','GOF','HAF','HAV','HUR','HOG','INN','KOL','SOF','OIS','NWY','NOR','NBU','NIA','VIP','RUT','SJV','SJN','SKY','FIN','STB','TID','TRO','TTS','ULR','UNI','VOT','VIL','VKT','VOG','NSB','GJB','VYG','VYB','VYX','OST','ATU'}

server.port=37998

publicationDeliveryStreamingOutput.validateAgainstSchema=true
netex.validPrefix=NMR
netex.profile.version=2.0:NO-NeTEx:2.0

autosys.api.api-key=${AUTOSYS_API_APIKEY}

#PUBLICATION_DELIVERY_STREAMING_OUTPUT_VALIDATE_AGAINST_SCHEMA=false
#NETEX_PROFILE_VERSION=1.12:NO-NeTEx-vehicle:1.4
#NETEX_VALIDPREFIX=NMR
#SHEPET_SECURITY_ROLE_ASSIGNMENT_EXTRACTOR=baba
#SHEPET_USER_PERMISSION_REST_SERVICE_URL=http://baba.dev.entur.internal/services/organisations/users
#SHEPET_OAUTH2_RESOURCESERVER_AUTH0_ENTUR_PARTNER_JWT_ISSUER_URI=https://partner.dev.entur.org/
#shepet.oauth2.resourceserver.auth0.entur.internal.jwt.audience=https://api.dev.entur.io
#SHEPET_OAUTH2_RESOURCESERVER_AUTH0_ENTUR_INTERNAL_JWT_ISSUER_URI=https://internal.dev.entur.org/
#SHEPET_OAUTH2_RESOURCESERVER_AUTH0_ENTUR_INTERNAL_JWT_AUDIENCE=https://api.dev.entur.io