sobek.locals.language.default=eng

debug=true

#OAuth2 Resource Server
sobek.oauth2.resourceserver.auth0.entur.partner.jwt.audience=https://api.dev.entur.io
sobek.oauth2.resourceserver.auth0.entur.partner.jwt.issuer-uri=https://partner.dev.entur.org/

# netex.valid.codespaces.list={'AKT','ATB','ASH','AVI','BNR','BEF','BOR','BSR','BRA','NYC','COL','TEL','FJT','FLI','FLT','FTR','FLB','OSC','MOR','GFS','GLO','GOA','GOF','HAF','HAV','HUR','HOG','INN','KOL','SOF','OIS','NWY','NOR','NBU','NIA','VIP','RUT','SJV','SJN','SKY','FIN','STB','TID','TRO','TTS','ULR','UNI','VOT','VIL','VKT','VOG','NSB','GJB','VYG','VYB','VYX','OST','ATU'}

server.port=37998

publicationDeliveryStreamingOutput.validateAgainstSchema=false
netex.validPrefix=NMR
netex.profile.version=1.12:NO-NeTEx-vehicle:1.4

autosys.api.api-key=${AUTOSYS_API_APIKEY}

