#OAuth2 Resource Server
shepet.oauth2.resourceserver.auth0.entur.partner.jwt.audience=${SHEPET_OAUTH2_RESOURCESERVER_AUTH0_ENTUR_PARTNER_JWT_AUDIENCE}
shepet.oauth2.resourceserver.auth0.entur.partner.jwt.issuer-uri=${SHEPET_OAUTH2_RESOURCESERVER_AUTH0_ENTUR_PARTNER_JWT_ISSUER_URI}

publicationDeliveryStreamingOutput.validateAgainstSchema=false
netex.validPrefix=NMR
netex.profile.version=2.0:NO-NeTEx:2.0

autosys.api.api-key=${AUTOSYS_API_APIKEY}