name: Build and push
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  maven-verify:
    env:
      JFROG_USER: ${{ secrets.ARTIFACTORY_AUTH_USER }}
      JFROG_PASS: ${{ secrets.ARTIFACTORY_AUTH_TOKEN }}
      AUTOSYS_API_APIKEY: ${{ secrets.AUTOSYS_API_APIKEY }}

    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - name: Copy maven settings
        run: |
          wget https://raw.githubusercontent.com/entur/ror-maven-settings/master/.m2/settings.xml -O .github/workflows/settings.xml
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            ${{ runner.os }}-maven-

      - name: Debug environment variable
        run: |
          if [ -z "$AUTOSYS_API_APIKEY" ]; then
            echo "AUTOSYS_API_APIKEY is not set"
          else
            echo "AUTOSYS_API_APIKEY is set (length: ${#AUTOSYS_API_APIKEY})"
          fi
      - name: Run maven build
        run: mvn -q verify -s .github/workflows/settings.xml
      - uses: actions/upload-artifact@v7.0.0
        with:
          path: shepet-app/target/*.jar

  docker-lint:
    needs: [maven-verify]
    uses: entur/gha-docker/.github/workflows/lint.yml@v1
    with:
      ignore: "DL3018"

  docker-build:
    if: github.repository_owner == 'entur' && github.event_name == 'push'
    needs: [maven-verify]
    uses: entur/gha-docker/.github/workflows/build.yml@v1
    with:
      build_artifact_name: artifact
      build_artifact_path: target
  docker-push:
    if: github.repository_owner == 'entur' && github.event_name == 'push'
    needs: [docker-build]
    uses: entur/gha-docker/.github/workflows/push.yml@v1

  docker-scan:
    needs: [ docker-build ]
    uses: entur/gha-security/.github/workflows/docker-scan.yml@v2
    with:
      image_artifact: ${{ needs.docker-build.outputs.image_artifact }}

  trigger-downstream-ci:
    if: github.repository_owner == 'entur' && github.event_name == 'push'
    needs: [docker-push]
    runs-on: ubuntu-latest
    steps:
        - name: Trigger downstream CI
          run: |
            repo_owner="entur"
            repo_name="shepet-deployment-config"
            event_type="trigger-downstream-ci"
            service="shepet"
            image_name=${{ needs.docker-push.outputs.image_name }}
            image_tag=${{ needs.docker-push.outputs.image_tag }} 
            echo "Triggering downstream CI for $service with version ${{ env.GHA_DOCKER_PUSH_IMAGE_TAG }}"
            curl -X POST \
            -H "Authorization: token ${{ secrets.GITFLOW_PAT }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Content-Type: application/json" https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"service\": \"$service\", \"image_name\": \"$image_name\", \"image_tag\": \"$image_tag\", \"unit\": false, \"integration\": true}}"